version: "3.5"
services:
  fin-diary.postgres:
    image: postgres:14-alpine
    container_name: fin-diary.postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - fin-diary.volume:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fin-diary.network

  fin-diary.pgadmin:
    image: dpage/pgadmin4
    container_name: fin-diary.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "fake@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8082:80"
    networks:
      - fin-diary.network

volumes:
  fin-diary.volume:

networks:
  fin-diary.network:
    driver: bridge
